name: Publish Package

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # For creating release
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  publish:
    needs: create_release
    runs-on: ubuntu-latest
    permissions:
      contents: write # For updating release
    strategy:
      matrix:
        file: ['arm64-linux', 'arm64-macos', 'x86_64-linux', 'x86_64-macos', 'x86_64-windows']
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build binaries
        run: |
          mkdir -p dist
          deno task compile:${{ matrix.file }}

      - name: Upload binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: dist/gpt-files-${{ matrix.file }}${{ matrix.file == 'x86_64-windows' && '.exe' || '' }}
          asset_name: gpt-files-${{ matrix.file }}${{ matrix.file == 'x86_64-windows' && '.exe' || '' }}
          asset_content_type: application/octet-stream

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run the installation command
        shell: pwsh
        run: |
          pwsh -NoProfile -ExecutionPolicy Bypass -Command "Invoke-WebRequest -UseBasicParsing https://raw.githubusercontent.com/Positive-LLC/gpt-files/refs/heads/main/install.ps1 | Invoke-Expression"

      - name: Run the test command
        shell: pwsh
        run: |
          gpt-files --help

  test-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run the installation command
        run: |
          curl -fsSL https://raw.githubusercontent.com/Positive-LLC/gpt-files/refs/heads/main/install.sh | sh

      - name: Run the test command
        run: |
          gpt-files --help
