name: Publish Package

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # For creating release
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  publish:
    needs: create_release
    runs-on: ubuntu-latest
    permissions:
      contents: write # For updating release
    strategy:
      matrix:
        file: ['arm64-linux', 'arm64-macos', 'x86_64-linux', 'x86_64-macos']
    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build binaries
        run: |
          mkdir -p dist
          deno task compile:${{ matrix.file }}

      - name: Upload binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/gpt-files-${{ matrix.file }}
          asset_name: gpt-files-${{ matrix.file }}
          asset_content_type: application/octet-stream